variables:
  GITLAB_NPM_URI: https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm
  GITLAB_NPM_TOKEN: $CI_JOB_TOKEN
  GITLAB_MAVEN_URI: https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/maven
  GITLAB_MAVEN_HEADER: Job-Token
  GITLAB_MAVEN_TOKEN: $CI_JOB_TOKEN

default:
  tags:
    - docker-runner-01
  image: registry.tenderhub.net/devops/docker/openjdk:21
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - publish

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

publish:npm:
  allow_failure: true
  stage: publish
  script:
    - ./gradlew publishBrowserPackageToGitlabRegistry

publish:browser:
  allow_failure: true
  stage: publish
  script:
    - ./gradlew publishBrowserPublicationToGitlabRepository

publish:android:debug:
  stage: publish
  image: registry.tenderhub.net/devops/docker/android-sdk:latest
  script:
    - ./gradlew publishAndroidDebugPublicationToGitlabRepository

publish:android:release:
  stage: publish
  image: registry.tenderhub.net/devops/docker/android-sdk:latest
  script:
    - ./gradlew publishAndroidReleasePublicationToGitlabRepository

publish:jvm:
  stage: publish
  script:
    - ./gradlew publishJvmPublicationToGitlabRepository

publish:multiplatform:
  stage: publish
  script:
    - ./gradlew publishKotlinMultiplatformPublicationToGitlabRepository