name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KOTLIN_KEY }}
      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}
      - name: Publish docs
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1
          arguments: dokkaHtml gitPublishPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}